grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
  image:
    tag: 8.4.3
  env:
    GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: k-8-s-packet-node-graph-plugin
  extraInitContainers:
    - name: local-plugins-downloader
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          #!/bin/sh
          set -euo pipefail
          mkdir -p /var/lib/grafana/plugins/node-graph-plugin
          cd /var/lib/grafana/plugins/node-graph-plugin
          for url in https://github.com/k8spacket/node-graph-plugin/releases/download/0.1.0/plugin.zip; do
            wget --no-check-certificate $url -O temp.zip
            unzip temp.zip
            rm temp.zip
          done
      volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
  datasources:
    node-graph-plugin-datasource.yaml:
      apiVersion: 1
      datasources:
      - name: "node-graph-plugin"
        access: "proxy"
        basicAuth: false
        isDefault: false
        readOnly: false
        type: "k-8-s-packet-node-graph-plugin"
        typeLogoUrl: "public/plugins/k-8-s-packet-node-graph-plugin/img/logo.svg"
        typeName: "node-graph-plugin"
        orgId: 1
        version: 1


