grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
  image:
    tag: 8.4.3
  env:
    GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: k8spacket-nodegraphplugin-datasource
  extraInitContainers:
    - name: local-plugins-downloader
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          #!/bin/sh
          set -euo pipefail
          echo "Install k8spacket plugin"
          mkdir -p /var/lib/grafana/plugins/node-graph-plugin
          cd /var/lib/grafana/plugins/node-graph-plugin
          for url in https://github.com/k8spacket/node-graph-plugin/releases/download/1.0.0/plugin.zip; do
            wget --no-check-certificate $url -O temp.zip
            unzip temp.zip
            rm temp.zip
          done
      volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana


